### ISSUE TITLE
Be able to search other languages, not only Javascript

### ISSUE THREAD

**Issue by bukinoshita** [bukinoshita/open-source#1]
For now we only search for Javascript issue, we want to be able to get from different languages as well.

**Comment by jackyho112** [comment]
Hello @bukinoshita, may I pick this one up?

**Comment by bukinoshita** [comment]
Go for it @jackyho112! ☺️

**Comment by bukinoshita** [comment]
First load should fetch the issues list of all languages and we have a select where we can filter the list per language. What do you think @jackyho112

**Comment by ribeiroevandro** [comment]
I found the idea and proposal very interesting, as I am intensifying my studies, I will collaborate with this project. 😊

**Comment by bukinoshita** [comment]
Awesome @ribeiroevandro! 🎉  Thanks so much for your feedback, will be so glad with your contributions!

**Comment by jackyho112** [comment]
@bukinoshita That sounds good. I have some ideas for implementation. Let me know what you think.

- get all issues in the `getInitialProps` with the `firstTimersOnly` tag
- I think we should get the language information for each issue and have a list of available languages with number of related issue information. The only way I know of to achieve this is to get the languages through the `languages_url` on each issue and then add that to each issue object in the array. But then that would require an API call for each issue which is pretty heavy. 
- I think we should also display the language information on each issue. For that, I will just modify the `listItem` component. 
- I'm not sure where the language options should be displayed. Maybe underneath the title and the description? For that, I'm thinking of just implementing inline buttons with the text, `'{language name} {number of related issues}'`.
- Now since the user can select a language to filter by, I think we should add a state called `languageFilter` to keep track of the current language filter. I will keep that state to the `OpenSource` component. 

Please let me know what you think. Obviously, the way I propose to retrieve the language information for each issue is not ideal. I am not 100% familiar with the Github API. If you have any alternative idea to add language information to each issue by using their API in some other ways, please share. 😄

**Comment by bukinoshita** [comment]
@jackyho112 awesome suggestions! Commenting my thoughts.

> get all issues in the getInitialProps with the firstTimersOnly tag

Sound good for me

---

> I think we should get the language information for each issue and have a list of available languages with number of related issue information. The only way I know of to achieve this is to get the languages through the languages_url on each issue and then add that to each issue object in the array. But then that would require an API call for each issue which is pretty heavy.

Yes, it might get pretty heavy fetching each item but it might not be a problem when we add pagination (infinite scroll) fetching 10 per 10(?) Idk. Would be great to fetch the repository info but still didn't find a solution without getting heavy.

---

> I think we should also display the language information on each issue. For that, I will just modify the listItem component.

Totally agree, I quickly prototype something for you.

---

> I'm not sure where the language options should be displayed. Maybe underneath the title and the description? For that, I'm thinking of just implementing inline buttons with the text, '{language name} {number of related issues}'.
Created a mockup for you to get an idea. But feel free to make changes. Not sure yet if this is the best solution, but I think we should follow on this direction and see how that goes. We can change the design later.

---

> Now since the user can select a language to filter by, I think we should add a state called languageFilter to keep track of the current language filter. I will keep that state to the OpenSource component.

Yeap! That sounds good!

![screenshot 2017-02-24 12 45 39](https://cloud.githubusercontent.com/assets/6929565/23314441/0d1a858a-fa90-11e6-8fc6-07dd9a39c3d0.png)

Based on your feedback I quickly prototyped this. I want to keep the language icon on top of the issue item (will provide all the svg's later here), not sure about the "filter" tho, but let's follow this design for now (feel free to make changes on this part ☺️ )

**Comment by jackyho112** [comment]
Everything looks good. I will start working on it and let you know how it goes.

**Comment by bukinoshita** [comment]
Awesome! Happy coding! 💯
